# Generated by Django 5.1.1 on 2024-09-25 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(models.DateField())]),
        ),
    ]
